# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  orderer.example.com:
  peer0.cirbus.example.com:
  peer0.soeing.example.com:
  peer0.nataair.example.com:
  peer0.lycanairsa.example.com:
  peer0.cengkarengairwayengineering.example.com:
  peer0.semco.example.com:
  peer0.aviparairline.example.com:
  peer0.pamulangairway.example.com:

networks:
  avipar:
    name: avipar_chain

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=6050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:6053
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:16050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 6050:6050
      - 6053:6053
      - 16050:16050
    networks:
      - avipar

  peer0.cirbus.example.com:
    container_name: peer0.cirbus.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=avipar_chain
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.cirbus.example.com
      - CORE_PEER_ADDRESS=peer0.cirbus.example.com:6051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6051
      - CORE_PEER_CHAINCODEADDRESS=peer0.cirbus.example.com:6052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cirbus.example.com:6051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.cirbus.example.com:6051
      - CORE_PEER_LOCALMSPID=CirbusMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:16051
    volumes:
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/cirbus.example.com/peers/peer0.cirbus.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/cirbus.example.com/peers/peer0.cirbus.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.cirbus.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 6051:6051
      - 16051:16051
    networks:
      - avipar

  peer0.soeing.example.com:
    container_name: peer0.soeing.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=avipar_chain
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.soeing.example.com
      - CORE_PEER_ADDRESS=peer0.soeing.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.soeing.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.soeing.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.soeing.example.com:7051
      - CORE_PEER_LOCALMSPID=SoeingMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17051
    volumes:
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/soeing.example.com/peers/peer0.soeing.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/soeing.example.com/peers/peer0.soeing.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.soeing.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 17051:17051
    networks:
      - avipar

  peer0.nataair.example.com:
    container_name: peer0.nataair.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=avipar_chain
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.nataair.example.com
      - CORE_PEER_ADDRESS=peer0.nataair.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.nataair.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nataair.example.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.nataair.example.com:8051
      - CORE_PEER_LOCALMSPID=NataAirMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:18051
    volumes:
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/nataair.example.com/peers/peer0.nataair.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/nataair.example.com/peers/peer0.nataair.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.nataair.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 8051:8051
      - 18051:18051
    networks:
      - avipar
  
  peer0.lycanairsa.example.com:
    container_name: peer0.lycanairsa.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=avipar_chain
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.lycanairsa.example.com
      - CORE_PEER_ADDRESS=peer0.lycanairsa.example.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.lycanairsa.example.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.lycanairsa.example.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.lycanairsa.example.com:10051
      - CORE_PEER_LOCALMSPID=LycanAirSAMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:11051
    volumes:
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/lycanairsa.example.com/peers/peer0.lycanairsa.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/lycanairsa.example.com/peers/peer0.lycanairsa.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.lycanairsa.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 10051:10051
      - 11051:11051
    networks:
      - avipar

  peer0.cengkarengairwayengineering.example.com:
    container_name: peer0.cengkarengairwayengineering.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=avipar_chain
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.cengkarengairwayengineering.example.com
      - CORE_PEER_ADDRESS=peer0.cengkarengairwayengineering.example.com:26051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:26051
      - CORE_PEER_CHAINCODEADDRESS=peer0.cengkarengairwayengineering.example.com:26052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:26052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cengkarengairwayengineering.example.com:26051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.cengkarengairwayengineering.example.com:26051
      - CORE_PEER_LOCALMSPID=CengkarengAirwayEngineeringMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:36051
    volumes:
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/cengkarengairwayengineering.example.com/peers/peer0.cengkarengairwayengineering.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/cengkarengairwayengineering.example.com/peers/peer0.cengkarengairwayengineering.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.cengkarengairwayengineering.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 26051:26051
      - 36051:36051
    networks:
      - avipar

  peer0.semco.example.com:
    container_name: peer0.semco.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=avipar_chain
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.semco.example.com
      - CORE_PEER_ADDRESS=peer0.semco.example.com:27051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:27051
      - CORE_PEER_CHAINCODEADDRESS=peer0.semco.example.com:27052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:27052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.semco.example.com:27051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.semco.example.com:27051
      - CORE_PEER_LOCALMSPID=SemcoMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:37051
    volumes:
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/semco.example.com/peers/peer0.semco.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/semco.example.com/peers/peer0.semco.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.semco.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 27051:27051
      - 37051:37051
    networks:
      - avipar

  peer0.aviparairline.example.com:
    container_name: peer0.aviparairline.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=avipar_chain
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.aviparairline.example.com
      - CORE_PEER_ADDRESS=peer0.aviparairline.example.com:28051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:28051
      - CORE_PEER_CHAINCODEADDRESS=peer0.aviparairline.example.com:28052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:28052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.aviparairline.example.com:28051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.aviparairline.example.com:28051
      - CORE_PEER_LOCALMSPID=AviparAirlineMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:38051
    volumes:
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/aviparairline.example.com/peers/peer0.aviparairline.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/aviparairline.example.com/peers/peer0.aviparairline.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.aviparairline.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 28051:28051
      - 38051:38051
    networks:
      - avipar
  
  peer0.pamulangairway.example.com:
    container_name: peer0.pamulangairway.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=avipar_chain
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.pamulangairway.example.com
      - CORE_PEER_ADDRESS=peer0.pamulangairway.example.com:29051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:29051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pamulangairway.example.com:29052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:29052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pamulangairway.example.com:29051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pamulangairway.example.com:29051
      - CORE_PEER_LOCALMSPID=PamulangAirwayMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:39051
    volumes:
        - ${DOCKER_SOCK}:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/pamulangairway.example.com/peers/peer0.pamulangairway.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/pamulangairway.example.com/peers/peer0.pamulangairway.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.pamulangairway.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 29051:29051
      - 39051:39051
    networks:
      - avipar

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.cirbus.example.com
      - peer0.soeing.example.com
      - peer0.nataair.example.com
      - peer0.lycanairsa.example.com
      - peer0.cengkarengairwayengineering.example.com
      - peer0.semco.example.com
      - peer0.aviparairline.example.com
      - peer0.pamulangairway.example.com
    networks:
      - avipar
